spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    initialization-mode: always
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  h2:
    console:
      enabled: true


logging:
  config: classpath:log4j2.xml
  level:
    org:
      hibernate:
        SQL: INFO #DEBUG for more information on SQL issued
        orm:
          jdbc:
            bind: INFO #TRACE for seeing bind parameters
